/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutoriasRouteImport } from './routes/tutorias'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as EnsinoIntegralRouteImport } from './routes/ensino-integral'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClubesRouteImport } from './routes/clubes'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as AEscolaRouteImport } from './routes/a-escola'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TurmasIndexRouteImport } from './routes/turmas.index'
import { Route as TurmasTurmaIdRouteImport } from './routes/turmas.$turmaId'

const TutoriasRoute = TutoriasRouteImport.update({
  id: '/tutorias',
  path: '/tutorias',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsinoIntegralRoute = EnsinoIntegralRouteImport.update({
  id: '/ensino-integral',
  path: '/ensino-integral',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesRoute = ClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const AEscolaRoute = AEscolaRouteImport.update({
  id: '/a-escola',
  path: '/a-escola',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasIndexRoute = TurmasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TurmasRoute,
} as any)
const TurmasTurmaIdRoute = TurmasTurmaIdRouteImport.update({
  id: '/$turmaId',
  path: '/$turmaId',
  getParentRoute: () => TurmasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-escola': typeof AEscolaRoute
  '/avisos': typeof AvisosRoute
  '/clubes': typeof ClubesRoute
  '/contato': typeof ContatoRoute
  '/ensino-integral': typeof EnsinoIntegralRoute
  '/equipe': typeof EquipeRoute
  '/eventos': typeof EventosRoute
  '/galeria': typeof GaleriaRoute
  '/turmas': typeof TurmasRouteWithChildren
  '/tutorias': typeof TutoriasRoute
  '/turmas/$turmaId': typeof TurmasTurmaIdRoute
  '/turmas/': typeof TurmasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-escola': typeof AEscolaRoute
  '/avisos': typeof AvisosRoute
  '/clubes': typeof ClubesRoute
  '/contato': typeof ContatoRoute
  '/ensino-integral': typeof EnsinoIntegralRoute
  '/equipe': typeof EquipeRoute
  '/eventos': typeof EventosRoute
  '/galeria': typeof GaleriaRoute
  '/tutorias': typeof TutoriasRoute
  '/turmas/$turmaId': typeof TurmasTurmaIdRoute
  '/turmas': typeof TurmasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-escola': typeof AEscolaRoute
  '/avisos': typeof AvisosRoute
  '/clubes': typeof ClubesRoute
  '/contato': typeof ContatoRoute
  '/ensino-integral': typeof EnsinoIntegralRoute
  '/equipe': typeof EquipeRoute
  '/eventos': typeof EventosRoute
  '/galeria': typeof GaleriaRoute
  '/turmas': typeof TurmasRouteWithChildren
  '/tutorias': typeof TutoriasRoute
  '/turmas/$turmaId': typeof TurmasTurmaIdRoute
  '/turmas/': typeof TurmasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-escola'
    | '/avisos'
    | '/clubes'
    | '/contato'
    | '/ensino-integral'
    | '/equipe'
    | '/eventos'
    | '/galeria'
    | '/turmas'
    | '/tutorias'
    | '/turmas/$turmaId'
    | '/turmas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-escola'
    | '/avisos'
    | '/clubes'
    | '/contato'
    | '/ensino-integral'
    | '/equipe'
    | '/eventos'
    | '/galeria'
    | '/tutorias'
    | '/turmas/$turmaId'
    | '/turmas'
  id:
    | '__root__'
    | '/'
    | '/a-escola'
    | '/avisos'
    | '/clubes'
    | '/contato'
    | '/ensino-integral'
    | '/equipe'
    | '/eventos'
    | '/galeria'
    | '/turmas'
    | '/tutorias'
    | '/turmas/$turmaId'
    | '/turmas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AEscolaRoute: typeof AEscolaRoute
  AvisosRoute: typeof AvisosRoute
  ClubesRoute: typeof ClubesRoute
  ContatoRoute: typeof ContatoRoute
  EnsinoIntegralRoute: typeof EnsinoIntegralRoute
  EquipeRoute: typeof EquipeRoute
  EventosRoute: typeof EventosRoute
  GaleriaRoute: typeof GaleriaRoute
  TurmasRoute: typeof TurmasRouteWithChildren
  TutoriasRoute: typeof TutoriasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorias': {
      id: '/tutorias'
      path: '/tutorias'
      fullPath: '/tutorias'
      preLoaderRoute: typeof TutoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensino-integral': {
      id: '/ensino-integral'
      path: '/ensino-integral'
      fullPath: '/ensino-integral'
      preLoaderRoute: typeof EnsinoIntegralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes': {
      id: '/clubes'
      path: '/clubes'
      fullPath: '/clubes'
      preLoaderRoute: typeof ClubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-escola': {
      id: '/a-escola'
      path: '/a-escola'
      fullPath: '/a-escola'
      preLoaderRoute: typeof AEscolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas/': {
      id: '/turmas/'
      path: '/'
      fullPath: '/turmas/'
      preLoaderRoute: typeof TurmasIndexRouteImport
      parentRoute: typeof TurmasRoute
    }
    '/turmas/$turmaId': {
      id: '/turmas/$turmaId'
      path: '/$turmaId'
      fullPath: '/turmas/$turmaId'
      preLoaderRoute: typeof TurmasTurmaIdRouteImport
      parentRoute: typeof TurmasRoute
    }
  }
}

interface TurmasRouteChildren {
  TurmasTurmaIdRoute: typeof TurmasTurmaIdRoute
  TurmasIndexRoute: typeof TurmasIndexRoute
}

const TurmasRouteChildren: TurmasRouteChildren = {
  TurmasTurmaIdRoute: TurmasTurmaIdRoute,
  TurmasIndexRoute: TurmasIndexRoute,
}

const TurmasRouteWithChildren =
  TurmasRoute._addFileChildren(TurmasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AEscolaRoute: AEscolaRoute,
  AvisosRoute: AvisosRoute,
  ClubesRoute: ClubesRoute,
  ContatoRoute: ContatoRoute,
  EnsinoIntegralRoute: EnsinoIntegralRoute,
  EquipeRoute: EquipeRoute,
  EventosRoute: EventosRoute,
  GaleriaRoute: GaleriaRoute,
  TurmasRoute: TurmasRouteWithChildren,
  TutoriasRoute: TutoriasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
